aps/urls.py
from django.conf.urls import url
from django.urls import path
from aps import views


app_name = 'aps'

urlpatterns=[
    url(r'^about/$',views.about,name='about'),
    url(r'^user_login/$',views.user_login,name='user_login'),
    url(r'^master_key_submit/$',views.master_key_submit,name='master_key_submit'),
    url(r'^create_key/$',views.create_key,name='create_key'),
    url(r'^list_key/$',views.list_key,name='list_key'),
    url(r'^create_key_submit/$',views.create_key_submit,name='create_key_submit'),
    url(r'^key_submit/$',views.key_submit,name='key_submit'),
    url(r'^master_key/$',views.master_key,name='master_key'),
    url(r'^validkey/$',views.validkey,name='validkey'),
    url(r'^validkeysubmit/$',views.validkeysubmit,name='validkeysubmit'),
    url(r'^rotate_key_master/$',views.rotate_key_master,name='rotate_key_master'),
    url(r'^delete_key_master/$',views.delete_key_master,name='delete_key_master'),
    url(r'^requestkey/$',views.requestkey,name='requestkey'),
    url(r'^caapprov/$',views.caapprov,name='caapprov'),   
    url(r'^keypairca/$',views.keypairca,name='keypairca'),  
    url(r'^listkeyca/$',views.listkeyca,name='listkeyca'),    
    url(r'^requestcsca/$',views.requestcsca,name='requestcsca'),
    url(r'^certificate/$',views.certifcate,name='certificate'),
    url(r'^certifcateINT/$',views.certifcateINT,name='certifcateINT'),
]

pki/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from aps import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.index,name='index'),
    url(r'^special/',views.special,name='special'),
    url(r'^aps/',include('aps.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
]

aps/models.py
#Database  

from django.db import models
from django.contrib.auth.models import User
from django.shortcuts import render
from django.db.models.signals import post_save
from django.dispatch import receiver

class Profile(models.Model):
    Admin = 1
    CSCA = 2
    DS = 3
    IS = 4
    MLS = 5
    DLS = 6
    ROLE_CHOICES = (
        (Admin, 'Administrator'),
        (CSCA, 'Country Signing Certification Authority'),
        (DS, 'Document Signer'),
        (IS, 'Inspection System'),
        (MLS, 'Master List Signer'),
        (DLS, 'Document List Signer'),
    )
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    role = models.PositiveSmallIntegerField(choices=ROLE_CHOICES, null=True, blank=True)

    def __str__(self):  
        return self.user.username

@receiver(post_save, sender=User)
def create_or_update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()

class UserProfileInfo(models.Model):
  user = models.OneToOneField(User,on_delete=models.CASCADE)
  portfolio_site = models.URLField(blank=True)
  profile_pic = models.ImageField(upload_to='profile_pics',blank=True)
  
  def __str__(self):
    return self.user.username

class mainkey(models.Model):
    no = models.AutoField(primary_key=True)
    id = models.CharField(max_length=100)
    key_name = models.TextField()
    time_start = models.TimeField()

    class Meta:
        managed = True
        db_table = 'mainkey'

    def __str__(self):
      return self.kunci

class PairKeyReq(models.Model):
    no = models.AutoField(primary_key=True)
    masterkey = models.CharField(max_length=100)
    organization = models.CharField(max_length=100,null=True)
    negara = models.CharField(max_length=100)
    kota = models.CharField(max_length=100)
    provinsi = models.CharField(max_length=100)            
    jalan = models.CharField(max_length=100)
    pos = models.CharField(max_length=100)
    status = models.CharField(max_length=10,null=True)        
    bit = models.FloatField(max_length=100,null=True)   
    jenis = models.FloatField(max_length=100,null=True)    
    privkey = models.TextField(null=True)    
    pubkey = models.TextField(null=True)    






    

aps/forms.py
from django import forms
from aps.models import UserProfileInfo
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','password','email')

class UserProfileInfoForm(forms.ModelForm):
     class Meta():
         model = UserProfileInfo
         fields = ('portfolio_site','profile_pic')

aps/views.py
#Pemanggilan Libary
from aps.forms import UserForm,UserProfileInfoForm
from cryptography.fernet import Fernet
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import ListView
from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives.asymmetric import rsa
from cryptography.hazmat.primitives.asymmetric import dsa
from cryptography.hazmat.primitives.asymmetric import ec
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives import serialization
from .models import mainkey,Profile,PairKeyReq
import base64
import datetime
import hvac
import mysql.connector
import pyautogui
import pybase64
import sys
import time

# Database Connection
db = mysql.connector.connect(host='localhost',database='pki',user='root',password='')
key = Fernet.generate_key()
f = Fernet(key)

client = hvac.Client(url='http://127.0.0.1:8200')

auth = Profile.objects.all()
job = {'auth': auth}

def index(request):
    return render(request,'aps/index.html')

@login_required
def create_key(request):

    test = mainkey.objects.all()[:1]
    context = {'test': test}

    return render(request, 'aps/newkey.html', context )   
    
@login_required
def create_key_submit(request):
    if request.method == 'POST':
        
        #sql_select_Query = "select kunci from mainkey where id = '{{comparison}}' "
        #cursor = db.cursor()
        #cursor.execute(sql_select_Query)
        
        #print(cursor.fetchall()) 
        
        #coba = f.decrypt(b) 
        #pyautogui.alert(coba)

        encrypttype = request.POST.get('encrypttype')
        bit         = request.POST.get('bit')    

        if encrypttype == 'RSA':

            if bit  =='512':
                bit = 512
            elif bit  =='1024':
                bit = 1024
            else :
                bit = 2048           
            
            encrypttype = encrypttype

            private_key_rsa = rsa.generate_private_key(
                public_exponent=65537,
                key_size= bit ,
                backend=default_backend()
            )

            kuncipub1 = private_key_rsa.private_bytes(
                encoding=serialization.Encoding.PEM,
                format=serialization.PrivateFormat.PKCS8,
                encryption_algorithm=serialization.BestAvailableEncryption(b'{{ encrypttype }}')
                )

            public_key = private_key_rsa.public_key()
            kuncipub = public_key.public_bytes(
                encoding=serialization.Encoding.PEM,
                format=serialization.PublicFormat.SubjectPublicKeyInfo
            )
                   
        elif encrypttype =='ECDSA':

            encrypttype = encrypttype

            private_key_ecdsa = ec.generate_private_key(
                ec.SECP384R1(), default_backend()
            )

            data = b"{{ encrypttype }}"
            
            signature = private_key_ecdsa.sign(
                data,
                ec.ECDSA(hashes.SHA256())
            ) 

            public_key = private_key_ecdsa.public_key()
            hasil = public_key.verify(signature, data, ec.ECDSA(hashes.SHA256()))

            kuncipub = hasil
            kuncipub1 = signature

        elif encrypttype =='DSA':

            if bit  =='1024':
                bit = 1024
            elif bit  =='2048':
                bit = 2048
            else :
                bit = 3072   

            encrypttype = encrypttype
            
            private_key_dsa = dsa.generate_private_key(
                key_size=bit,
                backend=default_backend()
            )

            data = b"{{ encrypttype }}"
            
            signature = private_key_dsa.sign(
                data,
                hashes.SHA256()
            )

            public_key = private_key_dsa.public_key()

            hasil = public_key.verify(
                signature,
                data,
                hashes.SHA256()
            )

            kuncipub = hasil
            kuncipub1 = signature

        elif encrypttype =='HASH':

            encrypttype = encrypttype

            if bit == 'SHA224': 
                key = hashes.SHA224()
            elif  bit == 'SHA256': 
                key = hashes.SHA256()  
            elif  bit == 'SHA384': 
                key = hashes.SHA384()
            else :
                key = hashes.SHA512()                

            digest = hashes.Hash(key, backend=default_backend())
            digest.update(b"{{ encrypttype }}")
            hasil = digest.finalize()

            kuncipub = 'none'
            kuncipub1 = hasil
        
        else :
            kuncipub = 'Failed'
            kuncipub1 = 'Failed'            
            
        context= {
            'public': kuncipub,
            'private':kuncipub1,
        }

        
        return render(request, 'aps/newkey.html',context)

    else :   
        pyautogui.alert('Failed')
        return render(request, 'aps/newkey.html')
      
@login_required
def key_submit(request):
    if request.method == 'POST':
        pyautogui.alert('Save Sucesfully')
        return render(request, 'aps/newkey.html')
    else :   
        pyautogui.alert('Failed')
        return render(request, 'aps/newkey.html')      

@login_required
def master_key(request):

    test = mainkey.objects.all()[:1]
    context = {'test': test}
    return render(request, 'aps/masterkey.html' , context ) 

@login_required
def master_key_submit(request):
        if request.method == 'POST':

            def base64ify(bytes_or_str):
                if sys.version_info[0] >= 3 and isinstance(bytes_or_str, str):
                    input_bytes = bytes_or_str.encode('utf8')
                else:
                    input_bytes = bytes_or_str

                output_bytes = base64.urlsafe_b64encode(input_bytes)
    
                if sys.version_info[0] >= 3:
                    return output_bytes.decode('ascii')
                else:
                    return output_bytes
            
            
            cursor = db.cursor(buffered=True)

            nik = request.POST.get('id')
            keyname = request.POST.get('keyname')


            client.secrets.transit.create_key(name=keyname)

            client.secrets.transit.update_key_configuration(
                name=keyname,                
                deletion_allowed=True,
                exportable=True,
            )

            export_key_response = client.secrets.transit.export_key(
                name=keyname,
                key_type='hmac-key',
            )

            ts = time.time()
            timestamp = (datetime.datetime.fromtimestamp(ts).strftime('%Y-%m-%d %H:%M:%S'))
            key = export_key_response['data']['keys']
        
            sql1 = "insert into mainkey(no, id, key_name, time_start) VALUES(%s, %s, %s, %s)"
            val = ("",nik,keyname,timestamp)

            cursor.execute(sql1,val)
            db.commit()

            pyautogui.alert('Master Key Created')
            return render(request, 'aps/index.html')  

        else :
            pyautogui.alert('Failed')  
            return render(request, 'aps/masterkey.html') 

@login_required
def special(request):
    return HttpResponse("You are logged in !")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def about(request):
    return render(request, 'aps/about.html')   

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request,user)

                return render(request, 'aps/index.html')

            else:
                return HttpResponse("Your account was inactive.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            pyautogui.alert('Please check again your Username or Password')
            return render(request, 'aps/login.html', {})
    else:
        return render(request, 'aps/login.html', {})

@login_required
def list_key(request):

    test = mainkey.objects.all()
    context = {'test': test}

    return render(request, 'aps/list_key.html', context)  

@login_required
def rotate_key_master(request) :
    if request.method == 'POST':
        keyname = request.POST.get('keyname')
        client.secrets.transit.rotate_key(name=keyname)
        pyautogui.alert('Rotete Key Sucess') 
        return render(request, 'aps/index.html') 
    else :
        pyautogui.alert('Rotete Key Failed')  
        return render(request, 'aps/list_key.html') 

@login_required
def delete_key_master(request) :
    if request.method == 'POST':
        keyname = request.POST.get('keydelete')

        cursor = db.cursor(buffered=True)
        
        sql1 = """Delete from mainkey where key_name = %s"""
        val = keyname
        cursor.execute(sql1,(val,))
        db.commit()

        client.secrets.transit.delete_key(name=keyname)
        pyautogui.alert('Delete Key Sucess') 
        return render(request, 'aps/index.html') 
    else :
        pyautogui.alert('Delete Keys Key Failed')  
        return render(request, 'aps/list_key.html') 

@login_required
def requestcsca(request):

    test = mainkey.objects.all()[:1]
    context = {'test': test}
    return render(request, 'aps/requestcsca.html', context) 

@login_required
def validkey(request):

    return render(request, 'aps/validkey.html')    

@login_required
def validkeysubmit(request):
    if request.method == 'POST':

templates/aps/base.html
<!DOCTYPE html>

<html> 
  <head>
    <meta charset="utf-8" >
    <title>PKI</title>
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
      <link href="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap-switch-button@1.0.0/css/bootstrap-switch-button.min.css" rel="stylesheet">  
      <script src="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap-switch-button@1.0.0/js/bootstrap-switch-button.min.js"></script>
      <script src='https://code.jquery.com/jquery-3.2.1.min.js'></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>    
      <style>
        .bs-example{
	        margin: 20px;
        }
        @media screen and (min-width: 768px) {
          .dropdown:hover .dropdown-menu, .btn-group:hover .dropdown-menu{
		        display: block;
	        }
	        .dropdown-menu{
		        margin-top: 0;
	        }
	        .dropdown-toggle{
		        margin-bottom: 2px;
	        }
	        .navbar .dropdown-toggle, .nav-tabs .dropdown-toggle{
		        margin-bottom: 0;
	        }
        }
</style>
<script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>

</head>
  <body>

  
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">


          <li><a class="navbar-link" href="{% url 'index' %}">Home</a></li>
          <li><a class="navbar-link" href="{% url 'aps:about' %}">About</a></li>    
          
          {% if user.is_authenticated %}
            {% if user.profile.role == 1 %}
              <li><a class="navbar-link" href="{% url 'admin:index' %}">Administrator </a></li> 
            {% endif %}
          {% endif %}  

          {% if user.is_authenticated %}
            {% if user.profile.role == 1 %}
              <li class="dropdown">
                <a href="#" data-toggle="dropdown" class="dropdown-toggle">Vault Setting <b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li><a href="{% url 'aps:validkey'%}">Configuration</a></li>
                  </ul>
              </li>
            {% endif %}
          {% endif %}

          {% if user.is_authenticated %}
            {% if user.profile.role == 1 %}
              <li class="dropdown">
                <a href="#" data-toggle="dropdown" class="dropdown-toggle">Master Key <b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li><a href="{% url 'aps:master_key' %}">Create</a></li>
                    <li><a href="{% url 'aps:list_key' %}">Key List</a></li>
                  </ul>
              </li>
            {% endif %}
          {% endif %}

          {% if user.is_authenticated %}
            {% if user.profile.role == 1 %}
              <li class="dropdown">
                <a href="#" data-toggle="dropdown" class="dropdown-toggle">Key Approval <b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li><a href="{% url 'aps:caapprov' %}">CA Approval</a></li>
                  </ul>
              </li>
            {% endif %}
          {% endif %}        

          {% if user.is_authenticated %}
            {% if user.profile.role == 1 %}
              <li class="dropdown">
                <a href="#" data-toggle="dropdown" class="dropdown-toggle">Key Log <b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li><a href="#">Country Signing CA</a></li>
                    <li><a href="#">Document Signers</a></li>
                    <li><a href="#">Inspection Systems</a></li>
                    <li><a href="#">Master List Signers</a></li>
                    <li><a href="#">Document List Signers</a></li>
                  </ul>
              </li>
            {% endif %}
          {% endif %}

          {% if user.is_authenticated %}
            {% if user.profile.role == 10 %}
              <li class="dropdown">
                <a href="#" data-toggle="dropdown" class="dropdown-toggle">Pair Key <b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li><a href="{% url 'aps:create_key' %}">Create</a></li>
                    <li><a href="#">List</a></li>
                  </ul>
              </li>
            {% endif %}
          {% endif %}

          {% if user.is_authenticated %}
            {% if user.profile.role == 2 %}
              <li class="dropdown">
                <a href="#" data-toggle="dropdown" class="dropdown-toggle">CSCA Key <b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li><a href="{% url 'aps:requestcsca' %}">Request Pair Key</a></li>
                    <li><a href="{% url 'aps:listkeyca' %}">List Pair Key</a></li>
                  </ul>
              </li>
            {% endif %}
          {% endif %}

          {% if user.is_authenticated %}
            {% if user.profile.role == 2 %}
              <li class="dropdown">
                <a href="#" data-toggle="dropdown" class="dropdown-toggle">Certificate <b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li><a href="{% url 'aps:certificate' %}">Create Certificate</a></li>
                    <li><a href="#">Approval Request Certificate</a></li>
                  </ul>
              </li>
            {% endif %}
          {% endif %}

          {% if user.is_authenticated %}
            {% if user.profile.role == 3 %}
              <li><a href="#">DS Key</a></li>
            {% endif %}
          {% endif %}     

          {% if user.is_authenticated %}
            {% if user.profile.role == 4 %}
              <li><a href="#">IS Key</a></li>
            {% endif %}
          {% endif %}   

          {% if user.is_authenticated %}
            {% if user.profile.role == 5 %}
              <li><a href="#">MLS Key</a></li>
            {% endif %}
          {% endif %}     

          {% if user.is_authenticated %}
            {% if user.profile.role == 6 %}
              <li><a href="#">DLS Key</a></li>
            {% endif %}
          {% endif %}     

          {% if user.is_authenticated %}
            <li><a href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'aps:user_login' %}">Login</a></li>
          {% endif %}

        </ul>
      
      </div>
    </nav>

    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>
    
  </body>
</html>

templates/aps/certificate.html
 {% extends 'aps/base.html' %}
{% block body_block %}

  <div class="container">
    <div class="jumbotron">
      <table class="table">
        <thead>
          <tr>
            <th class="text-center" scope="col">Main Key</th>
            <th class="text-center" scope="col">Request Certificate</th>
            <th class="text-center" scope="col">Certificate</th>
            <th class="text-center" scope="col">Self Sign</th>            
          </tr>
          </thead>  
          <tbody>
            <tr>
              <th class="text-center" scope="row">ff</th>
              <th class="text-center" scope="row">
                <form action="{% url 'aps:certifcateINT' %}" method ="POST">
                  {% csrf_token %}
                  <button class="btn btn-primary"><i class="fa fa-check"></i> </button>
                </form>  
              </th>
              <th class="text-center" scope="row"><button class="btn btn-primary"><i class="fa fa-check"></i>  </button></th>
              <th class="text-center" scope="row"><button class="btn btn-primary"><i class="fa fa-check"></i>  </button></th>
            </tr>  
          </tbody>         
      </table>

      </tbody>
    </div>
  </div>    

{% endblock %}      

templates/aps/list_key.html
{% extends "aps/base.html" %}
{% block body_block %}

<div class="container">
  <div class="jumbotron">
    <h5>
      <p align ="center">

      <table class="table">
        <thead>
            <tr>
                <th class="text-center" scope="col">ID</th>
                <th class="text-center" scope="col">Key Name</th>
                <th class="text-center" scope="col">Time Start</th>
                <th class="text-center" scope="col">Rotate Key</th>
                <th class="text-center" scope="col">Delete Key</th>
            </tr>
        </thead>  
        <tbody>
        {% for hasil in test %}

            <tr>
                <th class="text-center" scope="row">{{ hasil.id }} </th>
                <td class="text-center" >{{ hasil.key_name }}</td>
                <td class="text-center">{{ hasil.time_start }}</td>
                <td class="text-center">
                <form method="post" action="{% url 'aps:rotate_key_master' %}" >
                    {% csrf_token %}
                    <input hidden type ="text" id ="keyname" name = "keyname" value = "{{ hasil.key_name }}">
                    <button type="submit" class="btn btn-warning">V</button>
                </form>                
                </td>
                <td class="text-center">
                <form method="post" action="{% url 'aps:delete_key_master' %}" >
                    {% csrf_token %}
                    <input hidden type ="text" id ="keydelete" name = "keydelete" value = "{{ hasil.key_name }}">
                    <button type="submit" class="btn btn-delete">V</button>
                </form>   
                </td>
            </tr>    
        {% endfor %}             
        </tbody>
    </table>
      </p>
    </h5>
 </div>    
</div> 

{% endblock %}

templates/aps/login.html
{% extends 'aps/base.html' %}
{% block body_block %}

  <div class="container">
    <div class="jumbotron">
      <h3 align="center">Login  </h3>

      <div>
      </div>

      <form method="post" action="{% url 'aps:user_login' %}">
        {% csrf_token %}

        <div class="form-group row">
          <label class="form-label col-md-3" for="username">Username</label>
            <div class="col-md-9">
              <input type="text" name="username"
                maxlength="255"
                class="form-control form-control-sm"
                placeholder="Username" title="" required=""
                id="username">
            </div>
        </div>

        <div class="form-group row">
          <label class="form-label col-md-3" for="password">Password</label>
            <div class="col-md-9">
              <input type="password" name="password"
                maxlength="255"
                class="form-control form-control-sm"
                placeholder="Password" title="" required=""
                id="password">
            </div>
        </div>

        <div class="row">
          <div class="col-12 text-center">
            <div class="form-group">
              <button type="submit" class="form-button btn btn-success btn pull-right" >
              LOGIN
              </button>
            </div>
          </div>
        </div>
        
      </form>
    </div>
  </div>

{% endblock %}

templates/aps/masterkey.html
{% extends "aps/base.html" %}
{% block body_block %}

<div class="container">
  <div class="jumbotron">
    <h3>
      <p align ="center">
        Create Master Key
      </p>
    </h3>

    <form  method="post" action="{% url 'aps:master_key_submit' %}">
      {% csrf_token %}

        <div class="form-group row">
          <label class="form-label col-md-3" for="id">ID</label>
            <div class="col-md-9">
              <input readonly type="text" name="id"
                maxlength="255"
                class="form-control form-control-sm"
                 title="" required=""
                id="id" value = {{ user.id }} >
            </div>
        </div>

        <div class="form-group row">
          <label class="form-label col-md-3" for="keyname">Nama Kunci</label>
            <div class="col-md-9">
              <input readonly type="text" name="keyname"
                maxlength="255"
                class="form-control form-control-sm"
                 title="" required=""
                id="keyname" value = "{{ user.username }}" >
            </div>
        </div>

        <div class="row">
          <div class="col-12 text-center">
            <div class="form-group">
              <button type="submit" class="btn btn-primary btn-block" {% for hasil in test %}   
              {% if hasil.id >= '1' %} disabled  {% else %} enabled {% endif %}   {% endfor %} 
              onClick="history.go(0)">
              GENERATE
              </button>
            </div>
          </div>
        </div>

        <p></p>
        </form> 
            
</div>

{% endblock %}

templates/aps/newkey.html
{% extends "aps/base.html" %}
{% block body_block %}


<script language="javascript" type="text/javascript"> 

$(document).ready(function(){

var RSA = [
	{display: "512", value: "512" }, 
	{display: "1024", value: "1024" }, 
	{display: "2048", value: "2048" }]; 

var ECDSA = [
	{display: "256", value: "256" }, 
	{display: "512", value: "512" }, 
	{display: "1024", value: "1024" }, 
	{display: "2048", value: "2048" }]; 

var DSA = [ 
	{display: "1024",value: "1024" }, 
	{display: "2048",value: "2048" },
  {display: "3072", value: "3072" }];    
	
var HASH = [
	{display: "224", value: "SHA224" }, 
	{display: "256", value: "SHA256" }, 
	{display: "384", value: "SHA384" }, 
	{display: "512", value: "SHA512" }];  

$("#encrypttype").change(function() {
		var parent = $(this).val(); 
		
		switch(parent){ 
			  case 'RSA':
			 	list(RSA);
				break;
			  case 'HASH':
			 	list(HASH);
				break;	
			  case 'ECDSA':
			 	list(ECDSA);
				break;
        case 'DSA':
			 	list(DSA);
				break;	        		
			default: 
				$("#bit").html('');	 
				break;
		   }
});

function list(array_list)
{
	$("#bit").html(""); 
	$(array_list).each(function (i) {  
		$("#bit").append("<option value=\""+array_list[i].value+"\">"+array_list[i].display+"</option>");
	});
}

});

</script>

<div class="container">
  <div class="jumbotron">
    <h3>
      <p align ="center">
        Create New Key
      </p>
    </h3>

    <form method="post" action="{% url 'aps:create_key_submit' %}">
      {% csrf_token %}
              
        <div class="form-group row">
          <label class="form-label col-md-3" for="IDMaster">ID Master Key</label>
            <div class="col-md-9">
              <input readonly type="text" name="IDMaster" maxlength="255"  class="form-control form-control-sm" 
              title="" required="" id="IDMaster" value = "{% for hasil in test %} {{ hasil.id }} {% endfor %}" >
            </div>
        </div>

        <div class="form-group row">
          <label class="form-label col-md-3" for="encrypttype">Encryption Type</label>
            <div class="col-md-9">
              <select class="form-control" id="encrypttype" name="encrypttype">
                <option value =""></option>
                <option value ="RSA">RSA</option>
                <option value ="ECDSA">Elliptic Curve DSA  </option> 
                <option value ="DSA">Digital Signature Algorithm </option>
                <option value ="HASH">Hashing Algorithms </option>
              </select>
            </div>
        </div>

        <div class="form-group row">
          <label class="form-label col-md-3" for="bitrsa">Bit Lenghth</label>
            <div class="col-md-9">
              <select class="form-control" id="bit" name="bit">
              </select>
            </div>
        </div>

        <div class="row">
          <div class="col-12 text-center">
            <div class="form-group">
              <button type="submit" class="btn btn-primary btn-block" >
              GENERATE
              </button>
            </div>
          </div>
        </div>

        </form>

        <form  method="post" action="{% url 'aps:key_submit' %}">
          {% csrf_token %}
            <div class="form-group row">
              <label class="form-label col-md-3" for="public">Public Key</label>
                <div class="col-md-9">
                <textarea readonly type="text" name="public" rows="10"  class="form-control form-control-sm" 
                required="" id="public"> {{ public }}</textarea> 
              </div>
          </div>
            <div class="form-group row">
              <label class="form-label col-md-3" for="private">Private Key</label>
                <div class="col-md-9">
                <textarea readonly type="text" name="private" rows="10"  class="form-control form-control-sm" 
                required="" id="private" >{{ private }}</textarea>
              </div>
          </div>

        <div class="row">
          <div class="col-12 text-center">
            <div class="form-group">
              <button type="submit" class="btn btn-secondary btn-block" >
              SAVE
              </button>
            </div>
          </div>
        </div>

        </form>

        <p></p>
</div>


{% endblock %}